(()=>{(()=>{"use strict";var l={},E=(t=>(t[t.SCREEN_NOT_SUPPORTED=0]="SCREEN_NOT_SUPPORTED",t[t.SCREEN_WIDE=1]="SCREEN_WIDE",t[t.SCREEN_DESKTOP=2]="SCREEN_DESKTOP",t[t.SCREEN_TABLET=3]="SCREEN_TABLET",t[t.SCREEN_MOBILE=4]="SCREEN_MOBILE",t))(E||{}),o=Object.defineProperty,a=(t,e,r)=>e in t?o(t,e,{enumerable:!0,configurable:!0,writable:!0,value:r}):t[e]=r,i=(t,e,r)=>a(t,typeof e!="symbol"?e+"":e,r);class d{constructor(){i(this,"SCREEN_MOBILE_MIN_WIDTH",320),i(this,"SCREEN_MOBILE_MAX_WIDTH",767),i(this,"SCREEN_TABLET_MAX_WIDTH",991),i(this,"SCREEN_DESKTOP_MAX_WIDTH",1199),i(this,"EVENT_RESIZE","resize"),i(this,"EVENT_OPTIMIZED_RESIZE","optimizedResize"),i(this,"EVENT_SCREEN_TYPE_CHANGED","screenTypeChanged"),i(this,"optimizeResizeEvent",e=>{e=e||window;let r=!1;const n=()=>{r||(r=!0,requestAnimationFrame(()=>{e.dispatchEvent(new CustomEvent(this.EVENT_OPTIMIZED_RESIZE));const _=this.calcCurrent();window.screenHelperCurrent!==_&&(window.screenHelperCurrent=_,e.dispatchEvent(new CustomEvent(this.EVENT_SCREEN_TYPE_CHANGED))),r=!1}))};e.addEventListener(this.EVENT_RESIZE,n)})}get current(){return window.screenHelperCurrent===void 0&&(window.screenHelperCurrent=this.calcCurrent()),window.screenHelperCurrent}calcCurrent(){const e=document.querySelector('meta[name="screen-type-helper"]');if(e!==null)return parseInt(e.content,10);const r=window.matchMedia;if(r){if(r("(min-width: "+(this.SCREEN_DESKTOP_MAX_WIDTH+1)+"px)").matches)return E.SCREEN_WIDE;if(r("(min-width: "+(this.SCREEN_TABLET_MAX_WIDTH+1)+"px)").matches)return E.SCREEN_DESKTOP;if(r("(min-width: "+(this.SCREEN_MOBILE_MAX_WIDTH+1)+"px)").matches)return E.SCREEN_TABLET;if(r("(min-width: "+this.SCREEN_MOBILE_MIN_WIDTH+"px)").matches)return E.SCREEN_MOBILE}else{const n=window.innerWidth;if(n>this.SCREEN_DESKTOP_MAX_WIDTH)return E.SCREEN_WIDE;if(n>this.SCREEN_TABLET_MAX_WIDTH)return E.SCREEN_DESKTOP;if(n>this.SCREEN_MOBILE_MAX_WIDTH)return E.SCREEN_TABLET;if(n>=this.SCREEN_MOBILE_MIN_WIDTH)return E.SCREEN_MOBILE}return E.SCREEN_NOT_SUPPORTED}check(...e){for(const r of e)if(r===this.current)return!0;return!1}get isDesktop(){return this.check(E.SCREEN_DESKTOP,E.SCREEN_WIDE)}addResizeListener(e){this.optimizeResizeEvent(window),window.addEventListener(this.EVENT_OPTIMIZED_RESIZE,e)}removeResizeListener(e){window.removeEventListener(this.EVENT_OPTIMIZED_RESIZE,e)}addChangeScreenTypeListener(e){this.optimizeResizeEvent(window),window.addEventListener(this.EVENT_SCREEN_TYPE_CHANGED,e)}removeChangeScreenTypeListener(e){window.removeEventListener(this.EVENT_SCREEN_TYPE_CHANGED,e)}}const c=new d;window.initCategoryStories=t=>{const e=document.getElementById(t);e!==null&&([].slice.call(e.querySelectorAll("[data-video]")).forEach(r=>{r.addEventListener("click",n=>{n.preventDefault();const _=r.getAttribute("data-video"),s=window.modalProvider.getInstance({id:"cswm-"+t,headerHtml:"",modalClass:"category-stories__modal"});s.setHeader(r.getAttribute("data-video-title")),s.setContent(`
				<iframe
					class="category-stories__video"
					src="${_}"
					frameborder="0"
					allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
					allowfullscreen
					loading="lazy"
				></iframe>
			`),s.onHide(()=>{s.setContent("")}),s.show()})}),c.isDesktop?window.tns({container:e.querySelector("[data-wrap]"),slideBy:"page",controlsText:['<i class="category-stories__arrow category-stories__arrow_left"></i>','<i class="category-stories__arrow category-stories__arrow_right"></i>'],fixedWidth:205,loop:!1,rewind:!1,mouseDrag:!0,nav:!1,edgePadding:0,gutter:10,onInit:()=>{e.classList.remove("category-stories_loading")}}):e.classList.remove("category-stories_loading"))}})();})();
